name: main

on: [pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # needed to determine which packages to build
      - uses: git-for-windows/setup-git-for-windows-sdk@v1
        with:
          flavor: full
          msys: true
      - name: install pactoys (needed for `saneman`)
        shell: bash
        run: bash -lc "pacman -S --noconfirm pactoys"
      - name: CI-Build
        shell: bash
        run: bash -l .ci/ci-build.sh
        env:
          MSYSTEM: MSYS
          MAKEFLAGS: -j5
      - name: "Upload binaries"
        uses: actions/upload-artifact@v3
        with:
          name: msys2-packages
          path: artifacts/*.pkg.tar.*
